<?php
defined('BASEPATH') OR exit('No direct script access allowed');
?>

<div class="belhomme">
    <img class="belhommev2" src="img/chinoise1.jpg" alt="">
</div>

<div class="container">

    <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad at atque dolorem doloribus ducimus ex excepturi inventore itaque iure nulla numquam odio pariatur perspiciatis quidem, temporibus, ullam ut veniam voluptatibus.lorem  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam assumenda aut dolorum eum impedit nisi porro reiciendis, voluptas. Aperiam atque cumque ducimus ea eligendi ipsa non odit provident quam reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi assumenda autem fugiat, iusto ratione rem repellat rerum sapiente veritatis voluptate! Accusamus labore natus obcaecati officia quibusdam sapiente soluta tenetur voluptatibus.</p>
    <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad at atque dolorem doloribus ducimus ex excepturi inventore itaque iure nulla numquam odio pariatur perspiciatis quidem, temporibus, ullam ut veniam voluptatibus.lorem  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam assumenda aut dolorum eum impedit nisi porro reiciendis, voluptas. Aperiam atque cumque ducimus ea eligendi ipsa non odit provident quam reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi assumenda autem fugiat, iusto ratione rem repellat rerum sapiente veritatis voluptate! Accusamus labore natus obcaecati officia quibusdam sapiente soluta tenetur voluptatibus.</p>
    <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad at atque dolorem doloribus ducimus ex excepturi inventore itaque iure nulla numquam odio pariatur perspiciatis quidem, temporibus, ullam ut veniam voluptatibus.lorem  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam assumenda aut dolorum eum impedit nisi porro reiciendis, voluptas. Aperiam atque cumque ducimus ea eligendi ipsa non odit provident quam reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi assumenda autem fugiat, iusto ratione rem repellat rerum sapiente veritatis voluptate! Accusamus labore natus obcaecati officia quibusdam sapiente soluta tenetur voluptatibus.</p>
    <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad at atque dolorem doloribus ducimus ex excepturi inventore itaque iure nulla numquam odio pariatur perspiciatis quidem, temporibus, ullam ut veniam voluptatibus.lorem  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam assumenda aut dolorum eum impedit nisi porro reiciendis, voluptas. Aperiam atque cumque ducimus ea eligendi ipsa non odit provident quam reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi assumenda autem fugiat, iusto ratione rem repellat rerum sapiente veritatis voluptate! Accusamus labore natus obcaecati officia quibusdam sapiente soluta tenetur voluptatibus.</p>
    <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad at atque dolorem doloribus ducimus ex excepturi inventore itaque iure nulla numquam odio pariatur perspiciatis quidem, temporibus, ullam ut veniam voluptatibus.lorem  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam assumenda aut dolorum eum impedit nisi porro reiciendis, voluptas. Aperiam atque cumque ducimus ea eligendi ipsa non odit provident quam reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi assumenda autem fugiat, iusto ratione rem repellat rerum sapiente veritatis voluptate! Accusamus labore natus obcaecati officia quibusdam sapiente soluta tenetur voluptatibus.</p>
    <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad at atque dolorem doloribus ducimus ex excepturi inventore itaque iure nulla numquam odio pariatur perspiciatis quidem, temporibus, ullam ut veniam voluptatibus.lorem  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam assumenda aut dolorum eum impedit nisi porro reiciendis, voluptas. Aperiam atque cumque ducimus ea eligendi ipsa non odit provident quam reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi assumenda autem fugiat, iusto ratione rem repellat rerum sapiente veritatis voluptate! Accusamus labore natus obcaecati officia quibusdam sapiente soluta tenetur voluptatibus.</p><p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad at atque dolorem doloribus ducimus ex excepturi inventore itaque iure nulla numquam odio pariatur perspiciatis quidem, temporibus, ullam ut veniam voluptatibus.lorem  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam assumenda aut dolorum eum impedit nisi porro reiciendis, voluptas. Aperiam atque cumque ducimus ea eligendi ipsa non odit provident quam reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi assumenda autem fugiat, iusto ratione rem repellat rerum sapiente veritatis voluptate! Accusamus labore natus obcaecati officia quibusdam sapiente soluta tenetur voluptatibus.</p>



</div>

</body>
</html>